"""empty message

Revision ID: 3bbdde7ab2cf
Revises: 
Create Date: 2025-03-29 09:16:23.200515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbdde7ab2cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_table',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_username')
    )
    op.create_table('house_pictures_table',
    sa.Column('picture_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pictures', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('picture_id')
    )
    op.create_table('house_type',
    sa.Column('house_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('house_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('state_table',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('state_name')
    )
    op.create_table('tenant_details',
    sa.Column('tenant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_fname', sa.String(length=100), nullable=False),
    sa.Column('tenant_lname', sa.String(length=100), nullable=False),
    sa.Column('tenant_email', sa.String(length=100), nullable=False),
    sa.Column('tenant_phone', sa.String(length=100), nullable=False),
    sa.Column('tenant_password', sa.String(length=100), nullable=False),
    sa.Column('profile_pictures', sa.String(length=200), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('tenant_email'),
    sa.UniqueConstraint('tenant_phone')
    )
    op.create_table('landlord_details',
    sa.Column('landlord_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_fname', sa.String(length=100), nullable=False),
    sa.Column('landlord_lname', sa.String(length=100), nullable=False),
    sa.Column('landlord_email', sa.String(length=100), nullable=False),
    sa.Column('landlord_phone', sa.String(length=100), nullable=False),
    sa.Column('landlord_password', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('profile_pictures', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state_table.state_id'], ),
    sa.PrimaryKeyConstraint('landlord_id'),
    sa.UniqueConstraint('landlord_email'),
    sa.UniqueConstraint('landlord_phone')
    )
    op.create_table('chat_table',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_text', sa.Text(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('message_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord_details.landlord_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_details.tenant_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('vacant_houses',
    sa.Column('house_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('house_status', sa.Enum('active', 'inactive'), nullable=False),
    sa.Column('date_listed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord_details.landlord_id'], ),
    sa.PrimaryKeyConstraint('house_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacant_houses')
    op.drop_table('chat_table')
    op.drop_table('landlord_details')
    op.drop_table('tenant_details')
    op.drop_table('state_table')
    op.drop_table('house_type')
    op.drop_table('house_pictures_table')
    op.drop_table('admin_table')
    # ### end Alembic commands ###
