"""empty message

Revision ID: 48f1487b8736
Revises: 5a7a2107d87d
Create Date: 2025-04-11 11:35:49.188982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f1487b8736'
down_revision = '5a7a2107d87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint('bookmarks_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('bookmarks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant_details', ['user_id'], ['tenant_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vacant_houses', ['property_id'], ['house_id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_table', schema=None) as batch_op:
        batch_op.drop_constraint('chat_table_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('chat_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenant_details', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'landlord_details', ['landlord_id'], ['landlord_id'], ondelete='CASCADE')

    with op.batch_alter_table('house_pictures_table', schema=None) as batch_op:
        batch_op.drop_constraint('house_pictures_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vacant_houses', ['property_id'], ['house_id'], ondelete='CASCADE')

    with op.batch_alter_table('vacant_houses', schema=None) as batch_op:
        batch_op.drop_constraint('vacant_houses_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'landlord_details', ['landlord_id'], ['landlord_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacant_houses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vacant_houses_ibfk_1', 'landlord_details', ['landlord_id'], ['landlord_id'])

    with op.batch_alter_table('house_pictures_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('house_pictures_table_ibfk_1', 'vacant_houses', ['property_id'], ['house_id'])

    with op.batch_alter_table('chat_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_table_ibfk_1', 'landlord_details', ['landlord_id'], ['landlord_id'])
        batch_op.create_foreign_key('chat_table_ibfk_2', 'tenant_details', ['tenant_id'], ['tenant_id'])

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookmarks_ibfk_1', 'vacant_houses', ['property_id'], ['house_id'])
        batch_op.create_foreign_key('bookmarks_ibfk_2', 'tenant_details', ['user_id'], ['tenant_id'])

    # ### end Alembic commands ###
