"""empty message

Revision ID: 4a3de6011bb9
Revises: f257502241df
Create Date: 2025-04-05 15:18:09.890463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3de6011bb9'
down_revision = 'f257502241df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_pictures_table', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('house_pictures_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
