"""empty message

Revision ID: 57fdc0cca7a8
Revises: 869474a20f80
Create Date: 2025-03-30 10:01:23.606001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57fdc0cca7a8'
down_revision = '869474a20f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.alter_column('landlord_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('tenant_details', schema=None) as batch_op:
        batch_op.alter_column('tenant_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_details', schema=None) as batch_op:
        batch_op.alter_column('tenant_password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.alter_column('landlord_password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
