"""empty message

Revision ID: 70ef087fe755
Revises: 86a717ef33d2
Create Date: 2025-04-05 12:03:58.177340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ef087fe755'
down_revision = '86a717ef33d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_pictures_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vacant_houses', ['property_id'], ['house_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_pictures_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###
