"""empty message

Revision ID: 869474a20f80
Revises: da57d0d56f47
Create Date: 2025-03-30 09:09:13.806706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '869474a20f80'
down_revision = 'da57d0d56f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
