"""empty message

Revision ID: c752d6aa2769
Revises: df1e7a6b3b78
Create Date: 2025-04-05 19:02:32.438247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c752d6aa2769'
down_revision = 'df1e7a6b3b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacant_houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacant_houses', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
