"""empty message

Revision ID: da57d0d56f47
Revises: 3bbdde7ab2cf
Create Date: 2025-03-30 09:05:43.768147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da57d0d56f47'
down_revision = '3bbdde7ab2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.alter_column('landlord_phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('tenant_details', schema=None) as batch_op:
        batch_op.alter_column('tenant_phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_details', schema=None) as batch_op:
        batch_op.alter_column('tenant_phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('landlord_details', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('landlord_phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
