"""empty message

Revision ID: f257502241df
Revises: 70ef087fe755
Create Date: 2025-04-05 13:51:00.135444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f257502241df'
down_revision = '70ef087fe755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacant_houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'house_type', ['house_type_id'], ['house_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacant_houses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('house_type_id')

    # ### end Alembic commands ###
